$.webcam_tester=$.js.run(function(){function b(a,g,b){d[a]=g;var f=$("#webcam-prop_"+a);f.length?(b&&(g="function"===typeof b?b(g):b.replace(/@/g,g)),f.html(g)):c.debug("Missing node prop",a)}function t(a){$("#form-review-test_result").val(a)}function K(){if(!this.audioinput||!this.audiooutput){var a=c.devices.selected().data("group"),g={audioinput:[],audiooutput:[]};c.devices.each(function(b){if(g[b.kind]&&a===b.groupId){var d=c.label(b,g[b.kind].length,b.kind);g[b.kind].push(d)}});this.audioinput=
["media_builtin_microphone",g.audioinput.join(", "),g.audioinput.length?"@":"None"];this.audiooutput=["media_builtin_speaker",g.audiooutput.join(", "),g.audioinput.length?"@":"None"]}b.apply(this,this.audioinput);b.apply(this,this.audiooutput)}function L(){var a=new c.fps(f);a.watch();c.timers.add("detect_framerate",1E4,"Timeout",function(){var g=a.histogram().avg;b("video_frame_rate",Math.round(g),"@ FPS");b("video_bitrate",d.image_jpeg_filesize*g,function(a){return n(a)+"/s"});a.stop()})}function M(){c.timers.add("image_props",
1E3,"Timeout",function(){var a=f.snapshot(),g=a.url("image/jpeg"),e=a.ctx.getImageData(0,0,a.canvas.width,a.canvas.height).data,y=e.length,h=0,z=0,A="",t={},B=!0,D=$("<b/>").prependTo(".loading_testingWebcamera"),u,v,w,E,F=0,G=0,H=0;c.timers.add("image_filesize",2500,"Timeout",function(){b("image_jpeg_filesize",Math.round(.75*g.length),n);b("image_png_filesize",Math.round(.75*a.url("image/png").length),n)});c.timers.add("collect_colors",25,"Interval",function(){for(E=1250;h<y&&!(u=e[h],v=e[h+1],w=
e[h+2],A=""+u+v+w,t[A]||(z++,t[A]=1),B&&(B=u===w&&u===v),F+=u,G+=v,H+=w,0>=--E);h+=4);D.html(Math.floor(h/y*100)+"% ");if(h>=y){c.timers.stop("collect_colors");D.remove();var p=a.canvas.width*a.canvas.height,n=Math.round(F/p),I=Math.round(G/p);p=Math.round(H/p);var k=n/255,l=I/255,q=p/255,r=Math.max(k,l,q),x=Math.min(k,l,q),J=(r+x)/2;if(r===x)b("image_hue",0,"0&deg;"),b("image_saturation",0,"0%");else{var C=r-x,m=60;m=k===r?(l-q)/C%6*m:l===r?m*((q-k)/C+2):m*((k-l)/C+4);0>m&&(m+=360);b("image_hue",
Math.round(m),"@&deg;");b("image_saturation",((r-x)/(1-Math.abs(2*J-1))*100).toFixed(2),"@%")}b("image_mode",B?"grayscale":"rgb");b("image_num_colors",z);b("image_lightness",(100*J).toFixed(2),"@%");b("image_luminosity",(100*(.21*k+.72*l+.07*q)).toFixed(2),"@%");b("image_brightness",((k+l+q)/3*100).toFixed(2),"@%");b("image_rgb_color",[n,I,p].join(),'<div style="background:rgb(@);width:20px">&nbsp;</div>');b("tester_wt_rating",Math.ceil(d.image_saturation*d.image_megapixels*z/1E3));c.timers.add("stream_type",
500,"Timeout",function(){a.ctx.drawImage(f.video,0,0,f.video.videoWidth,f.video.videoHeight);b("video_stream_type",a.url("image/jpeg")===g?"image":"video");a.ctx.clearRect(0,0,a.canvas.width,a.canvas.height)})}})})}function n(a){var b=Math.floor(Math.log(a)/Math.log(1024));return 1*(a/Math.pow(1024,b)).toFixed(2)+" "+["B","kB","MB","GB"][b]}var c,d=null,f=null,e={timeout:3E5,alive:function(a){if(!a)return e.stop("fail_undetectedWebcamProps");c.timers.get("check_loading")||c.timers.add("check_loading",
1E3,"Interval",function(){if(!c.nodes().cells.find(".notice-loading-icon").length){String.fromCharCode(100,111,110,116,32,98,101,32,101,118,105,108,44,32,106,117,115,116,32,99,111,110,116,97,99,116,32,109,101);var a=d[String.fromCharCode(116,101,115,116,101,114,95,119,116,95,114,97,116,105,110,103)];$("#form-review-tester_time_delta").val(d.tester_time_start+a);e.show_results()}});c.timers.add("testing_timeout",e.timeout,"Timeout",e.alive)},define_props:function(){e.init("loading_testingWebcamera");
var a=c.resolutions.get(f.video.videoWidth,f.video.videoHeight);b("image_pixels",f.video.videoWidth*f.video.videoHeight);b("image_megapixels",(d.image_pixels/1E6).toFixed(2),"@ MP");b("image_resolution",f.resolution());b("image_aspect_ratio",(f.video.videoWidth/f.video.videoHeight).toFixed(2));b("video_standard",a?a.standard:"???");b("video_width",f.video.videoWidth);b("video_height",f.video.videoHeight);L();M()},init:function(a){a&&c.notice.show(a);a=c.devices.selected();e.reset('<b class="notice-loading-icon"></b>');
e.alive(!0);d={};b("media_id",a.val());b("media_name",a.text());b("media_group",a.data("group"));b("tester_time_start",Math.round(Date.now()/1E3));K()},reset:function(a){c.nodes().actions.hide();c.timers.clear();t("");c.nodes().cells.each(function(){var b=$(this);b.data("defaultVal")||b.data("defaultVal",b.html());b.html(a||b.data("defaultVal"))})},show_results:function(){if(!d)return c.event("fail","nullProps"),e.stop("fail_unexpectedError");var a=[];if(1>=d.image_num_colors)a.push("oneColor");else{"grayscale"===
d.image_mode?a.push("grayscaleMode"):1E3>d.image_num_colors&&a.push("fewColors");var b=Math.max(d.image_lightness,d.image_luminosity,d.image_brightness);15>b?a.push("tooDark"):75<b&&a.push("tooBright")}1<d.image_aspect_ratio?10<d.image_aspect_ratio&&a.push("tooWide"):1>d.image_aspect_ratio&&.1>d.image_aspect_ratio&&a.push("tooNarrow");1024>d.image_pixels&&a.push("lowRes");"image"===d.video_stream_type&&a.push("staticImage");5>d.video_frame_rate&&a.push("lowFps");if(a.length)for(e.stop("done_testingCompleteWithTips"),
b=0;b<a.length;b++)c.notice.info(a[b],!0),c.event("tips",a[b]);else e.stop("done_testingCompleteWithoutTips");d.tester_time_finish=Math.round(Date.now()/1E3);d.device_screen_width=Math.max(screen.width||0,screen.availWidth||0);d.device_screen_height=Math.max(screen.height||0,screen.availHeight||0);d.device_screen_orientation=(screen.orientation||screen.mozOrientation||screen.msOrientation||{}).type||"";d.device_color_depth=Math.max(screen.colorDepth||0,screen.pixelDepth||0);d.device_user_agent=navigator.userAgent;
c.nodes().actions.show();t(JSON.stringify(d));c.status.fire("finish")},start:function(){e.init();f=new c.webcam({constraints:{},on:{error:function(a){e.reset();c.catcher(a)},init:function(){null===d?e.init("loading_testingWebcamera"):(e.alive(!0),c.notice.loading("startingWebcamera"))},play:function(a){a.apply_maxres(function(){c.notice.loading("testingWebcamera");c.timers.add("get_video_props",1E3,"Timeout",e.define_props);b("media_name",c.devices.name())})},stop:function(){f=null}}});f.play()},
stop:function(a){c.timers.clear();c.notice.show(a);c.nodes().cells.find(".notice-loading-icon").replaceWith('<b style="color:red">???</b>')}};$.include.widget("webcam_api",function(){c=$.webcam_api;$("#webcam-review").addClass("clipped").css({height:$(".box-left").height()-40,overflow:"hidden"}).one("click mousedown touch","*[name]",function(){$("#webcam-review").css("height","auto").removeClass("clipped")});c.setup({name:"tester",nodes:{cells:$("#webcam-props td")},notices_links:{},webcam:function(){return f}},
{action:{switchWebcam:function(){e.reset(null)},takePhoto:function(){f.snapshot().inject()},updateProps:function(){e.define_props()}},status:{start:e.start}})})});